export const fonts2load = {
    GBold: require('./assets/fonts/GreycliffCF-Bold.otf'),
    GDemi: require('./assets/fonts/GreycliffCF-DemiBold.otf'),
    GMedium: require('./assets/fonts/GreycliffCF-Medium.otf'),
    GRegular: require('./assets/fonts/GreycliffCF-Regular.otf'),
    GLight: require('./assets/fonts/GreycliffCF-Light.otf'),
}

export const images2load = [
    require('./assets/img/avataaars.png'),
    require('./assets/img/collection.png'),
    require('./assets/img/gear.png'),
    require('./assets/img/xbtn.png'),
    require('./assets/img/home_dark.png'),
    require('./assets/img/home.png'),
    require('./assets/img/limited_edition_set.png'),
    require('./assets/img/login-image.png'),
    require('./assets/img/market_dark.png'),
    require('./assets/img/person_dark.png'),
    require('./assets/img/person.png'),
    require('./assets/img/Rectangle.png'),
    require('./assets/img/search.png'),
    require('./assets/img/start-image.png'),
    require('./assets/img/term_10.png'),
    require('./assets/img/term_100.png'),
    require('./assets/img/term_200.png'),
    require('./assets/img/wallpaper.png'),
    require('./assets/img/back_btn.png'),
    'https://res.cloudinary.com/devinroche/image/upload/v1534455400/buildings/state-of-georgia-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455400/buildings/willis-tower.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455400/buildings/Group_1_copy_2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455399/buildings/Group_1_12.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455399/buildings/Group_1_17.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455399/buildings/trump-tower-ny-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455397/buildings/Group_1_19.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455397/buildings/Group_1_16.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455397/buildings/Group_1_8.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455396/buildings/Group_1_15.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_18.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_11.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_9.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_14.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_13.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_5.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_10.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_7.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_3.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455395/buildings/Group_1_4.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455390/buildings/us-bank.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455390/buildings/Group_1_copy_4.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455390/buildings/Group_1_copy.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455389/buildings/seagram-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455388/buildings/Group_1.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455387/buildings/Group_1_copy_3.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455387/buildings/446-east-ontario.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455387/buildings/Group_1_1.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455386/buildings/cna-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455385/buildings/gp-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455385/buildings/181-w-madison.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455385/buildings/aon-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455385/buildings/Group_1_6.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455384/buildings/equitable-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1534455384/buildings/56-leonard-2.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1537208858/better-buildings/term_100.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1537208858/better-buildings/term_200.png',
    'https://res.cloudinary.com/devinroche/image/upload/v1537208858/better-buildings/term_10.png'
]