export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS';
export const TOGGLE_PROFILE_SEARCH = 'TOGGLE_PROFILE_SEARCH';
export const UPDATE_PROFILE_SEARCH = 'UPDATE_PROFILE_SEARCH'
export const UPDATE_MARKET_SEARCH = 'UPDATE_MARKET_SEARCH'