export const BUILDINGS_PENDING = "BUILDINGS_PENDING";
export const BUILDINGS_SUCCESS = "BUILDINGS_SUCCESS";
export const BUILDINGS_ERROR  = "BUILDINGS_ERROR ";
export const CURR_BUILDING = "CURR_BUILDING";